$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
    samples:
        type: string
    units:
        type: string
    outdir: 
        type: string
    
    parameters:
        properties:
            trimming:
                type: object
                properties:
                    adapter:
                        type: string
                    additional:
                        type: string
    
    resources:
        properties:
            default:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

            trim_adapters_single_end:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

            trim_adapters_paired_end:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

required:
    - samples
    - units
